var json = [{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":2,"Description":"Release Signature on File","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"0:20","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":3,"Description":"Incorrect Address","Date":"3-20-2018","Time":"0:25","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"0:30","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-20-2018","Time":"0:35","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"0:40","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"0:45","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":12,"Description":"Package Sorted to Wrong Route","Date":"3-20-2018","Time":"0:50","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-20-2018","Time":"0:55","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":8,"Description":"Not In/Business Closed","Date":"3-20-2018","Time":"1:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"13:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"14:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":2,"Description":"Release Signature on File","Date":"3-20-2018","Time":"15:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-20-2018","Time":"16:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"ORHA","Senior Manager":"Reginald Cruz","Type":"Station","State":"MA","Country":"US","LocNum":16,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"17:00","Division":"All","Region":"Eastern","District":"Bostonian","Location":"ORHA","LocNum":16},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"BEDA","Senior Manager":"Molly Fisher","Type":"Station","State":"MA","Country":"US","LocNum":21,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"BEDA","LocNum":21},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"NZWA","Senior Manager":"Lillie Barker","Type":"Station","State":"MA","Country":"US","LocNum":23,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"NZWA","LocNum":23},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"BVYA","Senior Manager":"Ian Barton","Type":"Station","State":"MA","Country":"US","LocNum":26,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"BVYA","LocNum":26},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"PVDA","Senior Manager":"Kelly Larson","Type":"Station","State":"RI","Country":"US","LocNum":29,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"PVDA","LocNum":29},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"PSMA","Senior Manager":"Aubrey Cook","Type":"Station","State":"NH","Country":"US","LocNum":38,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"PSMA","LocNum":38},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"BGRA","Senior Manager":"Sheila Fleming","Type":"Station","State":"ME","Country":"US","LocNum":44,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"BGRA","LocNum":44},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"AUGA","Senior Manager":"Jody Williamson","Type":"Station","State":"ME","Country":"US","LocNum":221,"DEX":3,"Description":"Incorrect Address","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"AUGA","LocNum":221},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"OWDA","Senior Manager":"Luke Richardson","Type":"Station","State":"MA","Country":"US","LocNum":238,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"OWDA","LocNum":238},
{"Division":"US Ops","Region":"Eastern","District":"Bostonian","Location":"CEFA","Senior Manager":"Clayton Curtis","Type":"Station","State":"MA","Country":"US","LocNum":269,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Bostonian","Location":"CEFA","LocNum":269},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"NYCA","Senior Manager":"Andre Hunter","Type":"Station","State":"NY","Country":"US","LocNum":100,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-20-2018","Time":"0:15","Division":"All","Region":"Eastern","District":"Big Apple","Location":"NYCA","LocNum":100},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"JRBA","Senior Manager":"Ricardo French","Type":"Station","State":"NY","Country":"US","LocNum":101,"DEX":12,"Description":"Package Sorted to Wrong Route","Date":"3-20-2018","Time":"0:20","Division":"All","Region":"Eastern","District":"Big Apple","Location":"JRBA","LocNum":101},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"WTCA","Senior Manager":"Pearl Howell","Type":"Station","State":"NY","Country":"US","LocNum":102,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"0:25","Division":"All","Region":"Eastern","District":"Big Apple","Location":"WTCA","LocNum":102},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"HPNA","Senior Manager":"Laverne Morgan","Type":"Station","State":"NY","Country":"US","LocNum":106,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"0:30","Division":"All","Region":"Eastern","District":"Big Apple","Location":"HPNA","LocNum":106},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"LGAA","Senior Manager":"Jeannie Owens","Type":"Station","State":"NY","Country":"US","LocNum":111,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"0:35","Division":"All","Region":"Eastern","District":"Big Apple","Location":"LGAA","LocNum":111},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"FIDA","Senior Manager":"June Benson","Type":"Station","State":"NY","Country":"US","LocNum":243,"DEX":11,"Description":"C O Delivery","Date":"3-20-2018","Time":"0:40","Division":"All","Region":"Eastern","District":"Big Apple","Location":"FIDA","LocNum":243},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"JRAA","Senior Manager":"Kerry Ballard","Type":"Station","State":"NY","Country":"US","LocNum":311,"DEX":8,"Description":"Not In/Business Closed","Date":"3-20-2018","Time":"0:45","Division":"All","Region":"Eastern","District":"Big Apple","Location":"JRAA","LocNum":311},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"TSSA","Senior Manager":"Caroline Long","Type":"Station","State":"NY","Country":"US","LocNum":316,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-20-2018","Time":"0:50","Division":"All","Region":"Eastern","District":"Big Apple","Location":"TSSA","LocNum":316},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"FBTA","Senior Manager":"Rodney Norton","Type":"Station","State":"NY","Country":"US","LocNum":372,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"0:55","Division":"All","Region":"Eastern","District":"Big Apple","Location":"FBTA","LocNum":372},
{"Division":"US Ops","Region":"Eastern","District":"Big Apple","Location":"FOKA","Senior Manager":"May Douglas","Type":"Station","State":"NY","Country":"US","LocNum":391,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"1:00","Division":"All","Region":"Eastern","District":"Big Apple","Location":"FOKA","LocNum":391},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"GAIA","Senior Manager":"Leona Watson","Type":"Station","State":"MD","Country":"US","LocNum":208,"DEX":2,"Description":"Release Signature on File","Date":"3-20-2018","Time":"1:05","Division":"All","Region":"Eastern","District":"Capital","Location":"GAIA","LocNum":208},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"HGRA","Senior Manager":"Mae Ortega","Type":"Station","State":"MD","Country":"US","LocNum":217,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-20-2018","Time":"1:10","Division":"All","Region":"Eastern","District":"Capital","Location":"HGRA","LocNum":217},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"DGNA","Senior Manager":"Jermaine Jones","Type":"Station","State":"VA","Country":"US","LocNum":224,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-20-2018","Time":"1:15","Division":"All","Region":"Eastern","District":"Capital","Location":"DGNA","LocNum":224},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"CHOA","Senior Manager":"Misty Cannon","Type":"Station","State":"VA","Country":"US","LocNum":229,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"1:20","Division":"All","Region":"Eastern","District":"Capital","Location":"CHOA","LocNum":229},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"ORFA","Senior Manager":"Matt Holloway","Type":"Station","State":"VA","Country":"US","LocNum":235,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"1:25","Division":"All","Region":"Eastern","District":"Capital","Location":"ORFA","LocNum":235},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"JPNA","Senior Manager":"Theodore Warner","Type":"Station","State":"DC","Country":"US","LocNum":246,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"1:30","Division":"All","Region":"Eastern","District":"Capital","Location":"JPNA","LocNum":246},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"MQIA","Senior Manager":"Mattie Christensen","Type":"Station","State":"NC","Country":"US","LocNum":263,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"1:35","Division":"All","Region":"Eastern","District":"Capital","Location":"MQIA","LocNum":263},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"PHFA","Senior Manager":"Ed Townsend","Type":"Station","State":"VA","Country":"US","LocNum":266,"DEX":11,"Description":"C O Delivery","Date":"3-20-2018","Time":"1:40","Division":"All","Region":"Eastern","District":"Capital","Location":"PHFA","LocNum":266},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"PTBA","Senior Manager":"Melinda Martin","Type":"Station","State":"VA","Country":"US","LocNum":271,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-20-2018","Time":"1:45","Division":"All","Region":"Eastern","District":"Capital","Location":"PTBA","LocNum":271},
{"Division":"US Ops","Region":"Eastern","District":"Capital","Location":"BCBA","Senior Manager":"Leroy Thompson","Type":"Station","State":"VA","Country":"US","LocNum":348,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"1:50","Division":"All","Region":"Eastern","District":"Capital","Location":"BCBA","LocNum":348},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"ZSYA","Senior Manager":"Melvin Carpenter","Type":"Station","State":"AZ","Country":"US","LocNum":127,"DEX":3,"Description":"Incorrect Address","Date":"3-20-2018","Time":"1:55","Division":"All","Region":"Western","District":"Canyon","Location":"ZSYA","LocNum":127},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"BTFA","Senior Manager":"Shelly Garner","Type":"Station","State":"UT","Country":"US","LocNum":297,"DEX":2,"Description":"Release Signature on File","Date":"3-20-2018","Time":"2:00","Division":"All","Region":"Western","District":"Canyon","Location":"BTFA","LocNum":297},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"MSCA","Senior Manager":"Kevin Stevenson","Type":"Station","State":"AZ","Country":"US","LocNum":397,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"2:05","Division":"All","Region":"Western","District":"Canyon","Location":"MSCA","LocNum":397},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"SGUA","Senior Manager":"Randall Clark","Type":"Station","State":"UT","Country":"US","LocNum":499,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"2:10","Division":"All","Region":"Western","District":"Canyon","Location":"SGUA","LocNum":499},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"OGDA","Senior Manager":"Hazel Tyler","Type":"Station","State":"UT","Country":"US","LocNum":574,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-20-2018","Time":"2:15","Division":"All","Region":"Western","District":"Canyon","Location":"OGDA","LocNum":574},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"VGTA","Senior Manager":"Laurence Harper","Type":"Station","State":"NV","Country":"US","LocNum":663,"DEX":17,"Description":"Customer Requested Future Delivery","Date":"3-20-2018","Time":"2:20","Division":"All","Region":"Western","District":"Canyon","Location":"VGTA","LocNum":663},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"JACA","Senior Manager":"Renee Cohen","Type":"Station","State":"WY","Country":"US","LocNum":793,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"2:25","Division":"All","Region":"Western","District":"Canyon","Location":"JACA","LocNum":793},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"ELPA","Senior Manager":"Gloria Medina","Type":"Station","State":"TX","Country":"US","LocNum":799,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"2:30","Division":"All","Region":"Western","District":"Canyon","Location":"ELPA","LocNum":799},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"LHUA","Senior Manager":"Adrian Day","Type":"Station","State":"AZ","Country":"US","LocNum":812,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"2:35","Division":"All","Region":"Western","District":"Canyon","Location":"LHUA","LocNum":812},
{"Division":"US Ops","Region":"Western","District":"Canyon","Location":"RKSA","Senior Manager":"Kelley Gross","Type":"Station","State":"WY","Country":"US","LocNum":830,"DEX":16,"Description":"Payment Received","Date":"3-20-2018","Time":"2:40","Division":"All","Region":"Western","District":"Canyon","Location":"RKSA","LocNum":830},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"BJCA","Senior Manager":"Leslie Watkins","Type":"Station","State":"CO","Country":"US","LocNum":457,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-20-2018","Time":"2:45","Division":"All","Region":"Western","District":"Mountain","Location":"BJCA","LocNum":457},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"WHHA","Senior Manager":"Erma Lowe","Type":"Station","State":"CO","Country":"US","LocNum":459,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-20-2018","Time":"2:50","Division":"All","Region":"Western","District":"Mountain","Location":"WHHA","LocNum":459},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"RIWA","Senior Manager":"Stacy Adkins","Type":"Station","State":"WY","Country":"US","LocNum":493,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-20-2018","Time":"2:55","Division":"All","Region":"Western","District":"Mountain","Location":"RIWA","LocNum":493},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"MTJA","Senior Manager":"Isaac Harris","Type":"Station","State":"CO","Country":"US","LocNum":497,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"3:00","Division":"All","Region":"Western","District":"Mountain","Location":"MTJA","LocNum":497},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"SBSA","Senior Manager":"Hubert Lambert","Type":"Station","State":"CO","Country":"US","LocNum":498,"DEX":3,"Description":"Incorrect Address","Date":"3-20-2018","Time":"3:05","Division":"All","Region":"Western","District":"Mountain","Location":"SBSA","LocNum":498},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"GCCA","Senior Manager":"Delores Knight","Type":"Station","State":"WY","Country":"US","LocNum":500,"DEX":5,"Description":"Customer Security Delay","Date":"3-20-2018","Time":"3:10","Division":"All","Region":"Western","District":"Mountain","Location":"GCCA","LocNum":500},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"SHRA","Senior Manager":"Cary Goodman","Type":"Station","State":"WY","Country":"US","LocNum":505,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-20-2018","Time":"3:15","Division":"All","Region":"Western","District":"Mountain","Location":"SHRA","LocNum":505},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"BKFA","Senior Manager":"Jorge Hansen","Type":"Station","State":"CO","Country":"US","LocNum":795,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-20-2018","Time":"3:20","Division":"All","Region":"Western","District":"Mountain","Location":"BKFA","LocNum":795},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"DENA","Senior Manager":"Jan Buchanan","Type":"Station","State":"CO","Country":"US","LocNum":802,"DEX":12,"Description":"Package Sorted to Wrong Route","Date":"3-21-2018","Time":"12:45","Division":"All","Region":"Western","District":"Mountain","Location":"DENA","LocNum":802},
{"Division":"US Ops","Region":"Western","District":"Mountain","Location":"FTCA","Senior Manager":"Terence Moreno","Type":"Station","State":"CO","Country":"US","LocNum":805,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-21-2018","Time":"13:00","Division":"All","Region":"Western","District":"Mountain","Location":"FTCA","LocNum":805},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"EATA","Senior Manager":"Tammy Davis","Type":"Station","State":"WA","Country":"US","LocNum":225,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"13:15","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"EATA","LocNum":225},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"BVUA","Senior Manager":"Percy Sharp","Type":"Station","State":"WA","Country":"US","LocNum":400,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"13:30","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"BVUA","LocNum":400},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"SEAA","Senior Manager":"Diane McCarthy","Type":"Station","State":"WA","Country":"US","LocNum":588,"DEX":11,"Description":"C O Delivery","Date":"3-21-2018","Time":"13:45","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"SEAA","LocNum":588},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"LMTA","Senior Manager":"Juanita Wright","Type":"Station","State":"OR","Country":"US","LocNum":715,"DEX":8,"Description":"Not In/Business Closed","Date":"3-21-2018","Time":"14:00","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"LMTA","LocNum":715},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"PAEA","Senior Manager":"Isabel Mann","Type":"Station","State":"WA","Country":"US","LocNum":728,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-21-2018","Time":"14:15","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"PAEA","LocNum":728},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"MFRA","Senior Manager":"Erin Bell","Type":"Station","State":"OR","Country":"US","LocNum":817,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"14:30","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"MFRA","LocNum":817},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"CLMA","Senior Manager":"Jill Bradley","Type":"Station","State":"WA","Country":"US","LocNum":822,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"14:45","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"CLMA","LocNum":822},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"HIOA","Senior Manager":"Terrence Pratt","Type":"Station","State":"OR","Country":"US","LocNum":825,"DEX":2,"Description":"Release Signature on File","Date":"3-21-2018","Time":"15:00","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"HIOA","LocNum":825},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"PDTA","Senior Manager":"Pauline Dean","Type":"Station","State":"OR","Country":"US","LocNum":832,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"15:15","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"PDTA","LocNum":832},
{"Division":"US Ops","Region":"Western","District":"Pacific Northwest","Location":"BOIA","Senior Manager":"Lisa Munoz","Type":"Station","State":"ID","Country":"US","LocNum":837,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"15:30","Division":"All","Region":"Western","District":"Pacific Northwest","Location":"BOIA","LocNum":837},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"LNNA","Senior Manager":"Gertrude Lawson","Type":"Station","State":"OH","Country":"US","LocNum":50,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"15:45","Division":"All","Region":"Central","District":"Three Rivers","Location":"LNNA","LocNum":50},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"PITA","Senior Manager":"Bessie Owen","Type":"Station","State":"PA","Country":"US","LocNum":152,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"16:00","Division":"All","Region":"Central","District":"Three Rivers","Location":"PITA","LocNum":152},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"AGCA","Senior Manager":"Amy Miller","Type":"Station","State":"PA","Country":"US","LocNum":154,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"16:15","Division":"All","Region":"Central","District":"Three Rivers","Location":"AGCA","LocNum":154},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"LBEA","Senior Manager":"Dallas Jenkins","Type":"Station","State":"PA","Country":"US","LocNum":156,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"16:30","Division":"All","Region":"Central","District":"Three Rivers","Location":"LBEA","LocNum":156},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"ERIA","Senior Manager":"Janice White","Type":"Station","State":"PA","Country":"US","LocNum":165,"DEX":11,"Description":"C O Delivery","Date":"3-21-2018","Time":"16:45","Division":"All","Region":"Central","District":"Three Rivers","Location":"ERIA","LocNum":165},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"AOOA","Senior Manager":"Marie Rose","Type":"Station","State":"PA","Country":"US","LocNum":166,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-21-2018","Time":"17:00","Division":"All","Region":"Central","District":"Three Rivers","Location":"AOOA","LocNum":166},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"JSTA","Senior Manager":"Lora Lee","Type":"Station","State":"PA","Country":"US","LocNum":169,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"17:15","Division":"All","Region":"Central","District":"Three Rivers","Location":"JSTA","LocNum":169},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"HLGA","Senior Manager":"Derek Garcia","Type":"Station","State":"WV","Country":"US","LocNum":260,"DEX":3,"Description":"Incorrect Address","Date":"3-21-2018","Time":"17:30","Division":"All","Region":"Central","District":"Three Rivers","Location":"HLGA","LocNum":260},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"MGWA","Senior Manager":"Victor Wolfe","Type":"Station","State":"WV","Country":"US","LocNum":265,"DEX":2,"Description":"Release Signature on File","Date":"3-21-2018","Time":"17:45","Division":"All","Region":"Central","District":"Three Rivers","Location":"MGWA","LocNum":265},
{"Division":"US Ops","Region":"Central","District":"Three Rivers","Location":"MEJA","Senior Manager":"Jon Santiago","Type":"Station","State":"PA","Country":"US","LocNum":281,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"18:00","Division":"All","Region":"Central","District":"Three Rivers","Location":"MEJA","LocNum":281},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"PLNA","Senior Manager":"Veronica Holmes","Type":"Station","State":"MI","Country":"US","LocNum":37,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"18:15","Division":"All","Region":"Central","District":"Great Lakes","Location":"PLNA","LocNum":37},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"CLUA","Senior Manager":"Deanna Byrd","Type":"Station","State":"IN","Country":"US","LocNum":279,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"18:30","Division":"All","Region":"Central","District":"Great Lakes","Location":"CLUA","LocNum":279},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"TOLA","Senior Manager":"Cindy Payne","Type":"Station","State":"OH","Country":"US","LocNum":436,"DEX":17,"Description":"Customer Requested Future Delivery","Date":"3-21-2018","Time":"18:45","Division":"All","Region":"Central","District":"Great Lakes","Location":"TOLA","LocNum":436},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"MZZA","Senior Manager":"Cheryl Mitchell","Type":"Station","State":"IN","Country":"US","LocNum":460,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"19:00","Division":"All","Region":"Central","District":"Great Lakes","Location":"MZZA","LocNum":460},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"FWAA","Senior Manager":"Sonja Patrick","Type":"Station","State":"IN","Country":"US","LocNum":468,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"19:15","Division":"All","Region":"Central","District":"Great Lakes","Location":"FWAA","LocNum":468},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"OKKA","Senior Manager":"Janet Harmon","Type":"Station","State":"IN","Country":"US","LocNum":469,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"19:30","Division":"All","Region":"Central","District":"Great Lakes","Location":"OKKA","LocNum":469},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"MIEA","Senior Manager":"Flora Collins","Type":"Station","State":"IN","Country":"US","LocNum":473,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"19:45","Division":"All","Region":"Central","District":"Great Lakes","Location":"MIEA","LocNum":473},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"BMGA","Senior Manager":"Mable Wells","Type":"Station","State":"IN","Country":"US","LocNum":474,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"20:00","Division":"All","Region":"Central","District":"Great Lakes","Location":"BMGA","LocNum":474},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"HUFA","Senior Manager":"Kellie Ray","Type":"Station","State":"IN","Country":"US","LocNum":478,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"20:15","Division":"All","Region":"Central","District":"Great Lakes","Location":"HUFA","LocNum":478},
{"Division":"US Ops","Region":"Central","District":"Great Lakes","Location":"LAFA","Senior Manager":"Inez May","Type":"Station","State":"IN","Country":"US","LocNum":479,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-21-2018","Time":"20:30","Division":"All","Region":"Central","District":"Great Lakes","Location":"LAFA","LocNum":479},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"ROAA","Senior Manager":"Sylvester Burgess","Type":"Station","State":"VA","Country":"US","LocNum":240,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"20:45","Division":"All","Region":"Central","District":"Piedmont","Location":"ROAA","LocNum":240},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"LYHA","Senior Manager":"Elaine Parker","Type":"Station","State":"VA","Country":"US","LocNum":245,"DEX":3,"Description":"Incorrect Address","Date":"3-21-2018","Time":"21:00","Division":"All","Region":"Central","District":"Piedmont","Location":"LYHA","LocNum":245},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"CRWA","Senior Manager":"Cameron Hart","Type":"Station","State":"WV","Country":"US","LocNum":253,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"21:15","Division":"All","Region":"Central","District":"Piedmont","Location":"CRWA","LocNum":253},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"PKBA","Senior Manager":"Howard Hines","Type":"Station","State":"WV","Country":"US","LocNum":261,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-21-2018","Time":"21:30","Division":"All","Region":"Central","District":"Piedmont","Location":"PKBA","LocNum":261},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"RDUA","Senior Manager":"Don Harrington","Type":"Station","State":"NC","Country":"US","LocNum":276,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-21-2018","Time":"21:45","Division":"All","Region":"Central","District":"Piedmont","Location":"RDUA","LocNum":276},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"RWIA","Senior Manager":"Corey Fuller","Type":"Station","State":"NC","Country":"US","LocNum":278,"DEX":12,"Description":"Package Sorted to Wrong Route","Date":"3-21-2018","Time":"22:00","Division":"All","Region":"Central","District":"Piedmont","Location":"RWIA","LocNum":278},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"HKYA","Senior Manager":"Chelsea Love","Type":"Station","State":"NC","Country":"US","LocNum":280,"DEX":4,"Description":"Delv'd to Add Other Than RCPT","Date":"3-21-2018","Time":"22:15","Division":"All","Region":"Central","District":"Piedmont","Location":"HKYA","LocNum":280},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"QWGA","Senior Manager":"Francis Russell","Type":"Station","State":"NC","Country":"US","LocNum":282,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"22:30","Division":"All","Region":"Central","District":"Piedmont","Location":"QWGA","LocNum":282},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"FAYA","Senior Manager":"Jerry Becker","Type":"Station","State":"NC","Country":"US","LocNum":283,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"22:45","Division":"All","Region":"Central","District":"Piedmont","Location":"FAYA","LocNum":283},
{"Division":"US Ops","Region":"Central","District":"Piedmont","Location":"MRNA","Senior Manager":"Lee Fitzgerald","Type":"Station","State":"NC","Country":"US","LocNum":355,"DEX":11,"Description":"C O Delivery","Date":"3-21-2018","Time":"23:00","Division":"All","Region":"Central","District":"Piedmont","Location":"MRNA","LocNum":355},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"RMGA","Senior Manager":"Jordan Casey","Type":"Station","State":"GA","Country":"US","LocNum":91,"DEX":8,"Description":"Not In/Business Closed","Date":"3-21-2018","Time":"23:15","Division":"All","Region":"Southern","District":"Southeast","Location":"RMGA","LocNum":91},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"AVLA","Senior Manager":"Ralph Webster","Type":"Station","State":"NC","Country":"US","LocNum":288,"DEX":1,"Description":"Pacage Not Delivered/Not Attempted","Date":"3-21-2018","Time":"23:30","Division":"All","Region":"Southern","District":"Southeast","Location":"AVLA","LocNum":288},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"GSPA","Senior Manager":"Kathleen Silva","Type":"Station","State":"SC","Country":"US","LocNum":296,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"23:45","Division":"All","Region":"Southern","District":"Southeast","Location":"GSPA","LocNum":296},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"ANDA","Senior Manager":"Crystal Norris","Type":"Station","State":"SC","Country":"US","LocNum":298,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"23:40","Division":"All","Region":"Southern","District":"Southeast","Location":"ANDA","LocNum":298},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"FTYA","Senior Manager":"Pat Ford","Type":"Station","State":"GA","Country":"US","LocNum":300,"DEX":2,"Description":"Released Signature on File","Date":"3-21-2018","Time":"23:35","Division":"All","Region":"Southern","District":"Southeast","Location":"FTYA","LocNum":300},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"MGEA","Senior Manager":"Douglas Nelson","Type":"Station","State":"GA","Country":"US","LocNum":302,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"23:30","Division":"All","Region":"Southern","District":"Southeast","Location":"MGEA","LocNum":302},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"AHNA","Senior Manager":"Pete Griffin","Type":"Station","State":"GA","Country":"US","LocNum":306,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"23:25","Division":"All","Region":"Southern","District":"Southeast","Location":"AHNA","LocNum":306},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"NCQA","Senior Manager":"Roosevelt Wade","Type":"Station","State":"GA","Country":"US","LocNum":308,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"23:20","Division":"All","Region":"Southern","District":"Southeast","Location":"NCQA","LocNum":308},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"AGSA","Senior Manager":"Daisy Blake","Type":"Station","State":"GA","Country":"US","LocNum":309,"DEX":6,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"23:15","Division":"All","Region":"Southern","District":"Southeast","Location":"AGSA","LocNum":309},
{"Division":"US Ops","Region":"Southern","District":"Southeast","Location":"MCNA","Senior Manager":"Homer Chapman","Type":"Station","State":"GA","Country":"US","LocNum":312,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"23:10","Division":"All","Region":"Southern","District":"Southeast","Location":"MCNA","LocNum":312},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"BCTA","Senior Manager":"Jessie Sims","Type":"Station","State":"FL","Country":"US","LocNum":2,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"23:05","Division":"All","Region":"Southern","District":"South Florida","Location":"BCTA","LocNum":2},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"TMBA","Senior Manager":"Dawn Norman","Type":"Station","State":"FL","Country":"US","LocNum":10,"DEX":11,"Description":"C O Delivery","Date":"3-21-2018","Time":"23:00","Division":"All","Region":"Southern","District":"South Florida","Location":"TMBA","LocNum":10},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"HSTA","Senior Manager":"Maria Bell","Type":"Station","State":"FL","Country":"US","LocNum":14,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-21-2018","Time":"22:55","Division":"All","Region":"Southern","District":"South Florida","Location":"HSTA","LocNum":14},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"PBIA","Senior Manager":"Rita Bowers","Type":"Station","State":"FL","Country":"US","LocNum":334,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"22:50","Division":"All","Region":"Southern","District":"South Florida","Location":"PBIA","LocNum":334},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"SRQA","Senior Manager":"Bert Hubbard","Type":"Station","State":"FL","Country":"US","LocNum":335,"DEX":3,"Description":"Incorrect Address","Date":"3-21-2018","Time":"22:45","Division":"All","Region":"Southern","District":"South Florida","Location":"SRQA","LocNum":335},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"PIEA","Senior Manager":"Gladys Ryan","Type":"Station","State":"FL","Country":"US","LocNum":337,"DEX":2,"Description":"Release Signature on File","Date":"3-21-2018","Time":"22:40","Division":"All","Region":"Southern","District":"South Florida","Location":"PIEA","LocNum":337},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"LALA","Senior Manager":"Stephanie Stewart","Type":"Station","State":"FL","Country":"US","LocNum":338,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"22:35","Division":"All","Region":"Southern","District":"South Florida","Location":"LALA","LocNum":338},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"FMYA","Senior Manager":"Al Rios","Type":"Station","State":"FL","Country":"US","LocNum":339,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"22:30","Division":"All","Region":"Southern","District":"South Florida","Location":"FMYA","LocNum":339},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"FPRA","Senior Manager":"Bobbie Schwartz","Type":"Station","State":"FL","Country":"US","LocNum":340,"DEX":7,"Description":"Shipment Refused by Recipient","Date":"3-21-2018","Time":"22:25","Division":"All","Region":"Southern","District":"South Florida","Location":"FPRA","LocNum":340},
{"Division":"US Ops","Region":"Southern","District":"South Florida","Location":"APFA","Senior Manager":"Kristina Joseph","Type":"Station","State":"FL","Country":"US","LocNum":385,"DEX":17,"Description":"Customer Requested Future Delivery","Date":"3-21-2018","Time":"22:20","Division":"All","Region":"Southern","District":"South Florida","Location":"APFA","LocNum":385},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"MQYA","Senior Manager":"Luz Jennings","Type":"Station","State":"TN","Country":"US","LocNum":369,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"22:15","Division":"All","Region":"Southern","District":"Delta","Location":"MQYA","LocNum":369},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"BNAA","Senior Manager":"Melinda Chapman","Type":"Station","State":"TN","Country":"US","LocNum":370,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"22:10","Division":"All","Region":"Southern","District":"Delta","Location":"BNAA","LocNum":370},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"OLVA","Senior Manager":"Lyle Brock","Type":"Station","State":"TN","Country":"US","LocNum":380,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"22:05","Division":"All","Region":"Southern","District":"Delta","Location":"OLVA","LocNum":380},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"MKLA","Senior Manager":"Mitchell Daniel","Type":"Station","State":"TN","Country":"US","LocNum":383,"DEX":16,"Description":"Payment Received","Date":"3-21-2018","Time":"22:00","Division":"All","Region":"Southern","District":"Delta","Location":"MKLA","LocNum":383},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"TUPA","Senior Manager":"Olga Rodriquez","Type":"Station","State":"MS","Country":"US","LocNum":388,"DEX":10,"Description":"Damaged - Delivery Not Completed","Date":"3-21-2018","Time":"21:55","Division":"All","Region":"Southern","District":"Delta","Location":"TUPA","LocNum":388},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"CRXA","Senior Manager":"Flora Vega","Type":"Station","State":"MS","Country":"US","LocNum":430,"DEX":15,"Description":"Business Closed Due to Strike","Date":"3-21-2018","Time":"21:50","Division":"All","Region":"Southern","District":"Delta","Location":"CRXA","LocNum":430},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"BWGA","Senior Manager":"Tammy Gordon","Type":"Station","State":"KY","Country":"US","LocNum":540,"DEX":9,"Description":"Damaged - Delivery Completed","Date":"3-21-2018","Time":"21:45","Division":"All","Region":"Southern","District":"Delta","Location":"BWGA","LocNum":540},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"LITA","Senior Manager":"Israel Lawson","Type":"Station","State":"AR","Country":"US","LocNum":722,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"21:40","Division":"All","Region":"Southern","District":"Delta","Location":"LITA","LocNum":722},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"OKCA","Senior Manager":"Silvia Boyd","Type":"Station","State":"OK","Country":"US","LocNum":723,"DEX":3,"Description":"Incorrect Address","Date":"3-21-2018","Time":"21:35","Division":"All","Region":"Southern","District":"Delta","Location":"OKCA","LocNum":723},
{"Division":"US Ops","Region":"Southern","District":"Delta","Location":"JBRA","Senior Manager":"Donna Gardner","Type":"Station","State":"AR","Country":"US","LocNum":724,"DEX":5,"Description":"Customer Security Delay","Date":"3-21-2018","Time":"21:30","Division":"All","Region":"Southern","District":"Delta","Location":"JBRA","LocNum":724}]


var all_dex = [];
var all_labels = [];
var dummy_data = [];
var dex_count = [];
var labels = [];
var exists = 0;

for(var i =0; i<json.length;i++){
	all_dex.push(json[i].DEX);
	all_labels.push(json[i].Description);
}

for(var i=0; i <= all_dex.length; i++){
	if(dummy_data.length == 0){
		dummy_data.push(all_dex[i]);
		labels.push(all_labels[i]);
		dex_count.push(1);
	}
	exists = 0;
	for(var j=0; j <= dummy_data.length; j++){
		if(all_dex[i] == dummy_data[j]){
			dex_count[j]++;
			exists = 1;
			break;
		}
	}
	if(exists != 1){
		dummy_data.push(all_dex[i]);
		labels.push(all_labels[i]);
		dex_count.push(1);
	}

	
}
dex_count.pop();

console.log(labels);
console.log(dummy_data);
console.log(dex_count);


var chart = document.getElementById('polarAreaChartCanvas');
console.log(chart);
var polarAreaChart = new Chart(chart, {
	data: {
		datasets: [{
        data: dex_count,
		backgroundColor: ["#660066","#ff00ff","#ff99ff","#ccccff","#6699ff","#0033cc","#00ccff","#99ffcc","#00ff00","#009900","#ccff99","#ffcc00","#ff6600","#ff5050","#993333","#cc6699"],
		}],

		// These labels appear in the legend and in the tooltips when hovering different arcs
		labels: labels
	},
	type: 'polarArea',
	hoverRadius: 0,
	options: {
        legend: {
            display:true,
			position: 'right',
			responsive: false,
			//labels: {
			//	usePointStyle: true
			//}
        }
	}
	
	
});